title: Evan Thomas # your name (or website title) here
logo: "/images/website_headshot.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  GES master's student 
  <br><br>
  UMBC
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
